language: node_js
node_js:
  - "0.12"
before_install :
  - npm install -g bower gulp
  - gem install scss scss_lint scss_lint_reporter_checkstyle

before_script : "bower install"

cache:
  directories:
    - node_modules

script:
  - gulp dev
  - gulp prod

after_success: "bash scripts/build_n_push.sh"
